// This file was generated by Mendix Business Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package profileservice.proxies;

import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixIdentifier;
import com.mendix.systemwideinterfaces.core.IMendixObject;

/**
 * 
 */
public class UserProfile
{
	private final IMendixObject userProfileMendixObject;

	private final IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final String entityName = "ProfileService.UserProfile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OpenId("OpenId"),
		DisplayName("DisplayName"),
		EmailAddress("EmailAddress"),
		AvatarUrl("AvatarUrl"),
		AvatarThumbnailUrl("AvatarThumbnailUrl"),
		JobTitle("JobTitle"),
		Department("Department"),
		Location("Location"),
		Country("Country"),
		Bio("Bio"),
		Website("Website"),
		Phone("Phone"),
		LinkedIn("LinkedIn"),
		Twitter("Twitter"),
		Skype("Skype"),
		CompanyId("CompanyId"),
		Company("Company"),
		UserProfile_Company("ProfileService.UserProfile_Company");

		private String metaName;

		MemberNames(String s)
		{
			metaName = s;
		}

		@Override
		public String toString()
		{
			return metaName;
		}
	}

	public UserProfile(IContext context)
	{
		this(context, Core.instantiate(context, "ProfileService.UserProfile"));
	}

	protected UserProfile(IContext context, IMendixObject userProfileMendixObject)
	{
		if (userProfileMendixObject == null)
			throw new IllegalArgumentException("The given object cannot be null.");
		if (!Core.isSubClassOf("ProfileService.UserProfile", userProfileMendixObject.getType()))
			throw new IllegalArgumentException("The given object is not a ProfileService.UserProfile");

		this.userProfileMendixObject = userProfileMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UserProfile.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static profileservice.proxies.UserProfile initialize(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		return profileservice.proxies.UserProfile.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.getSudoContext() can be used to obtain sudo access).
	 */
	public static profileservice.proxies.UserProfile initialize(IContext context, IMendixObject mendixObject)
	{
		return new profileservice.proxies.UserProfile(context, mendixObject);
	}

	public static profileservice.proxies.UserProfile load(IContext context, IMendixIdentifier mendixIdentifier) throws CoreException
	{
		IMendixObject mendixObject = Core.retrieveId(context, mendixIdentifier);
		return profileservice.proxies.UserProfile.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(IContext context) throws CoreException
	{
		Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(IContext context)
	{
		Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of OpenId
	 */
	public final String getOpenId()
	{
		return getOpenId(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenId
	 */
	public final String getOpenId(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.OpenId.toString());
	}

	/**
	 * Set value of OpenId
	 * @param openid
	 */
	public final void setOpenId(String openid)
	{
		setOpenId(getContext(), openid);
	}

	/**
	 * Set value of OpenId
	 * @param context
	 * @param openid
	 */
	public final void setOpenId(IContext context, String openid)
	{
		getMendixObject().setValue(context, MemberNames.OpenId.toString(), openid);
	}

	/**
	 * @return value of DisplayName
	 */
	public final String getDisplayName()
	{
		return getDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of DisplayName
	 */
	public final String getDisplayName(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.DisplayName.toString());
	}

	/**
	 * Set value of DisplayName
	 * @param displayname
	 */
	public final void setDisplayName(String displayname)
	{
		setDisplayName(getContext(), displayname);
	}

	/**
	 * Set value of DisplayName
	 * @param context
	 * @param displayname
	 */
	public final void setDisplayName(IContext context, String displayname)
	{
		getMendixObject().setValue(context, MemberNames.DisplayName.toString(), displayname);
	}

	/**
	 * @return value of EmailAddress
	 */
	public final String getEmailAddress()
	{
		return getEmailAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAddress
	 */
	public final String getEmailAddress(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.EmailAddress.toString());
	}

	/**
	 * Set value of EmailAddress
	 * @param emailaddress
	 */
	public final void setEmailAddress(String emailaddress)
	{
		setEmailAddress(getContext(), emailaddress);
	}

	/**
	 * Set value of EmailAddress
	 * @param context
	 * @param emailaddress
	 */
	public final void setEmailAddress(IContext context, String emailaddress)
	{
		getMendixObject().setValue(context, MemberNames.EmailAddress.toString(), emailaddress);
	}

	/**
	 * @return value of AvatarUrl
	 */
	public final String getAvatarUrl()
	{
		return getAvatarUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of AvatarUrl
	 */
	public final String getAvatarUrl(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AvatarUrl.toString());
	}

	/**
	 * Set value of AvatarUrl
	 * @param avatarurl
	 */
	public final void setAvatarUrl(String avatarurl)
	{
		setAvatarUrl(getContext(), avatarurl);
	}

	/**
	 * Set value of AvatarUrl
	 * @param context
	 * @param avatarurl
	 */
	public final void setAvatarUrl(IContext context, String avatarurl)
	{
		getMendixObject().setValue(context, MemberNames.AvatarUrl.toString(), avatarurl);
	}

	/**
	 * @return value of AvatarThumbnailUrl
	 */
	public final String getAvatarThumbnailUrl()
	{
		return getAvatarThumbnailUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of AvatarThumbnailUrl
	 */
	public final String getAvatarThumbnailUrl(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.AvatarThumbnailUrl.toString());
	}

	/**
	 * Set value of AvatarThumbnailUrl
	 * @param avatarthumbnailurl
	 */
	public final void setAvatarThumbnailUrl(String avatarthumbnailurl)
	{
		setAvatarThumbnailUrl(getContext(), avatarthumbnailurl);
	}

	/**
	 * Set value of AvatarThumbnailUrl
	 * @param context
	 * @param avatarthumbnailurl
	 */
	public final void setAvatarThumbnailUrl(IContext context, String avatarthumbnailurl)
	{
		getMendixObject().setValue(context, MemberNames.AvatarThumbnailUrl.toString(), avatarthumbnailurl);
	}

	/**
	 * @return value of JobTitle
	 */
	public final String getJobTitle()
	{
		return getJobTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of JobTitle
	 */
	public final String getJobTitle(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.JobTitle.toString());
	}

	/**
	 * Set value of JobTitle
	 * @param jobtitle
	 */
	public final void setJobTitle(String jobtitle)
	{
		setJobTitle(getContext(), jobtitle);
	}

	/**
	 * Set value of JobTitle
	 * @param context
	 * @param jobtitle
	 */
	public final void setJobTitle(IContext context, String jobtitle)
	{
		getMendixObject().setValue(context, MemberNames.JobTitle.toString(), jobtitle);
	}

	/**
	 * @return value of Department
	 */
	public final String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final String getDepartment(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(IContext context, String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	/**
	 * @return value of Location
	 */
	public final String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final String getLocation(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(IContext context, String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Country
	 */
	public final String getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final String getCountry(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Country.toString());
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(String country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(IContext context, String country)
	{
		getMendixObject().setValue(context, MemberNames.Country.toString(), country);
	}

	/**
	 * @return value of Bio
	 */
	public final String getBio()
	{
		return getBio(getContext());
	}

	/**
	 * @param context
	 * @return value of Bio
	 */
	public final String getBio(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Bio.toString());
	}

	/**
	 * Set value of Bio
	 * @param bio
	 */
	public final void setBio(String bio)
	{
		setBio(getContext(), bio);
	}

	/**
	 * Set value of Bio
	 * @param context
	 * @param bio
	 */
	public final void setBio(IContext context, String bio)
	{
		getMendixObject().setValue(context, MemberNames.Bio.toString(), bio);
	}

	/**
	 * @return value of Website
	 */
	public final String getWebsite()
	{
		return getWebsite(getContext());
	}

	/**
	 * @param context
	 * @return value of Website
	 */
	public final String getWebsite(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Website.toString());
	}

	/**
	 * Set value of Website
	 * @param website
	 */
	public final void setWebsite(String website)
	{
		setWebsite(getContext(), website);
	}

	/**
	 * Set value of Website
	 * @param context
	 * @param website
	 */
	public final void setWebsite(IContext context, String website)
	{
		getMendixObject().setValue(context, MemberNames.Website.toString(), website);
	}

	/**
	 * @return value of Phone
	 */
	public final String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final String getPhone(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(IContext context, String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of LinkedIn
	 */
	public final String getLinkedIn()
	{
		return getLinkedIn(getContext());
	}

	/**
	 * @param context
	 * @return value of LinkedIn
	 */
	public final String getLinkedIn(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.LinkedIn.toString());
	}

	/**
	 * Set value of LinkedIn
	 * @param linkedin
	 */
	public final void setLinkedIn(String linkedin)
	{
		setLinkedIn(getContext(), linkedin);
	}

	/**
	 * Set value of LinkedIn
	 * @param context
	 * @param linkedin
	 */
	public final void setLinkedIn(IContext context, String linkedin)
	{
		getMendixObject().setValue(context, MemberNames.LinkedIn.toString(), linkedin);
	}

	/**
	 * @return value of Twitter
	 */
	public final String getTwitter()
	{
		return getTwitter(getContext());
	}

	/**
	 * @param context
	 * @return value of Twitter
	 */
	public final String getTwitter(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Twitter.toString());
	}

	/**
	 * Set value of Twitter
	 * @param twitter
	 */
	public final void setTwitter(String twitter)
	{
		setTwitter(getContext(), twitter);
	}

	/**
	 * Set value of Twitter
	 * @param context
	 * @param twitter
	 */
	public final void setTwitter(IContext context, String twitter)
	{
		getMendixObject().setValue(context, MemberNames.Twitter.toString(), twitter);
	}

	/**
	 * @return value of Skype
	 */
	public final String getSkype()
	{
		return getSkype(getContext());
	}

	/**
	 * @param context
	 * @return value of Skype
	 */
	public final String getSkype(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Skype.toString());
	}

	/**
	 * Set value of Skype
	 * @param skype
	 */
	public final void setSkype(String skype)
	{
		setSkype(getContext(), skype);
	}

	/**
	 * Set value of Skype
	 * @param context
	 * @param skype
	 */
	public final void setSkype(IContext context, String skype)
	{
		getMendixObject().setValue(context, MemberNames.Skype.toString(), skype);
	}

	/**
	 * @return value of CompanyId
	 */
	public final String getCompanyId()
	{
		return getCompanyId(getContext());
	}

	/**
	 * @param context
	 * @return value of CompanyId
	 */
	public final String getCompanyId(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.CompanyId.toString());
	}

	/**
	 * Set value of CompanyId
	 * @param companyid
	 */
	public final void setCompanyId(String companyid)
	{
		setCompanyId(getContext(), companyid);
	}

	/**
	 * Set value of CompanyId
	 * @param context
	 * @param companyid
	 */
	public final void setCompanyId(IContext context, String companyid)
	{
		getMendixObject().setValue(context, MemberNames.CompanyId.toString(), companyid);
	}

	/**
	 * @return value of Company
	 */
	public final String getCompany()
	{
		return getCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Company
	 */
	public final String getCompany(IContext context)
	{
		return (String) getMendixObject().getValue(context, MemberNames.Company.toString());
	}

	/**
	 * Set value of Company
	 * @param company
	 */
	public final void setCompany(String company)
	{
		setCompany(getContext(), company);
	}

	/**
	 * Set value of Company
	 * @param context
	 * @param company
	 */
	public final void setCompany(IContext context, String company)
	{
		getMendixObject().setValue(context, MemberNames.Company.toString(), company);
	}

	/**
	 * @return value of UserProfile_Company
	 */
	public final profileservice.proxies.Company getUserProfile_Company() throws CoreException
	{
		return getUserProfile_Company(getContext());
	}

	/**
	 * @param context
	 * @return value of UserProfile_Company
	 */
	public final profileservice.proxies.Company getUserProfile_Company(IContext context) throws CoreException
	{
		profileservice.proxies.Company result = null;
		IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserProfile_Company.toString());
		if (identifier != null)
			result = profileservice.proxies.Company.load(context, identifier);
		return result;
	}

	/**
	 * Set value of UserProfile_Company
	 * @param userprofile_company
	 */
	public final void setUserProfile_Company(profileservice.proxies.Company userprofile_company)
	{
		setUserProfile_Company(getContext(), userprofile_company);
	}

	/**
	 * Set value of UserProfile_Company
	 * @param context
	 * @param userprofile_company
	 */
	public final void setUserProfile_Company(IContext context, profileservice.proxies.Company userprofile_company)
	{
		if (userprofile_company == null)
			getMendixObject().setValue(context, MemberNames.UserProfile_Company.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.UserProfile_Company.toString(), userprofile_company.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final IMendixObject getMendixObject()
	{
		return userProfileMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final profileservice.proxies.UserProfile that = (profileservice.proxies.UserProfile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static String getType()
	{
		return "ProfileService.UserProfile";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
